# **PyTorch**

**Tensors** (https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)


As opposed to Python Lists, Tensors have a fixed, pre-defined size:

In [155]:
import torch

zeros = torch.zeros(3,6) #3 rows, 6 columns, filled with zeros
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [156]:
ones = torch.ones(6,3) #6 rows, 3 columns, filled with ones
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [157]:
random = torch.rand(6,6) #6 rows, 6 columns, filled with random values
random

tensor([[0.1574, 0.9144, 0.4728, 0.2691, 0.5082, 0.0695],
        [0.5497, 0.8965, 0.4052, 0.0376, 0.3466, 0.5884],
        [0.6614, 0.2324, 0.2847, 0.3588, 0.8572, 0.8256],
        [0.1864, 0.7117, 0.6588, 0.3715, 0.1489, 0.4006],
        [0.3606, 0.8524, 0.2853, 0.6764, 0.5063, 0.6005],
        [0.8602, 0.5437, 0.5186, 0.4448, 0.6609, 0.2008]])

In [158]:
exampleList = [[1,2,3],[3,2,1]] #tensor from list
exampleTensor = torch.tensor(exampleList)
exampleTensor

tensor([[1, 2, 3],
        [3, 2, 1]])

In [159]:
torch.arange(6) #fill with numbers

tensor([0, 1, 2, 3, 4, 5])

**Tensor Attributes**

In [160]:
random.shape #overall dimensionality

torch.Size([6, 6])

In [161]:
random.dtype #the data type of values

torch.float32

In [162]:
random.device #location of a tensor

device(type='cpu')



---


# Operations

For many operations, the dimension(s) on which to operate on need to be specified

In [163]:
torch.sum(exampleTensor,0) #calculate the sums along dimension zero

tensor([4, 4, 4])

In [164]:
torch.sum(exampleTensor,1) #calculate the sums along dimension one

tensor([6, 6])

**Be aware of dimensions!**

In [165]:
torch.sum(exampleTensor,2) #attempting to calculate the sums along (non-existing) dimension 2

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

**Many operations work on both scalars and tensors:**

In [166]:
exampleTensor/2 #divide every element by two

tensor([[0.5000, 1.0000, 1.5000],
        [1.5000, 1.0000, 0.5000]])

In [167]:
exampleTensor*2 #multiply every elememt by two

tensor([[2, 4, 6],
        [6, 4, 2]])

In [168]:
exampleTensor+2 #add two to every element

tensor([[3, 4, 5],
        [5, 4, 3]])

In [169]:
exampleTensor+exampleTensor #perform an element-wise addition of two tensors

tensor([[2, 4, 6],
        [6, 4, 2]])

In [170]:
exampleTensor*exampleTensor #perform an element-wise multiplication of two tensors

tensor([[1, 4, 9],
        [9, 4, 1]])

**The shapes of the tensors involved need to match for the given operation!**

In [171]:
zeros + ones #size mismatch

RuntimeError: The size of tensor a (6) must match the size of tensor b (3) at non-singleton dimension 1

**Matrix transpose can help to enable certain operations**

In [172]:
zeros.transpose(0,1) + ones #matrix transpose

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [173]:
zeros + ones.transpose(0,1)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [174]:
twos = ones+ones
twos

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [175]:
sixes = twos+twos+twos
torch.div(sixes,twos) #element-wise divison

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [176]:
torch.log(sixes) #calculate log for every element

tensor([[1.7918, 1.7918, 1.7918],
        [1.7918, 1.7918, 1.7918],
        [1.7918, 1.7918, 1.7918],
        [1.7918, 1.7918, 1.7918],
        [1.7918, 1.7918, 1.7918],
        [1.7918, 1.7918, 1.7918]])

In [177]:
torch.count_nonzero(sixes) #get the total amount of non-zero values

tensor(18)



---


# Accessing and changing tensor values by their index:

In [178]:
sixes[0,1] = 0 #set the specified value to zero
sixes

tensor([[6., 0., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

In [179]:
replacement = torch.Tensor([4,1,5])
sixes[0,:] = replacement #change a complete row

sixes

tensor([[4., 1., 5.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])

In [180]:
sixes[:,0] #get first element of every row

tensor([4., 6., 6., 6., 6., 6.])

In [181]:
sixes[0,:] #get first element of every column

tensor([4., 1., 5.])



---

# Similarity measures

In [182]:
a = torch.rand(5)
b = torch.rand(5)

print (a)
print (b)

tensor([0.3551, 0.6023, 0.1756, 0.6900, 0.4046])
tensor([0.6629, 0.2121, 0.4736, 0.7645, 0.7948])


In [183]:
torch.dot(a,b) #dot product; will be zero if vectors are orthogonal

tensor(1.2954)

In [184]:
torch.cosine_similarity(a,b,0) #disregarding vector magnitude

tensor(0.8671)

In [185]:
vector1 = torch.Tensor([1,1])
vector2 = torch.Tensor([2,2])

In [186]:
torch.cosine_similarity(vector1,vector2,dim=0) #only takes into account the angle

tensor(1.0000)

In [187]:
torch.dot(vector1,vector2) #takes into account both angle and magnitude

tensor(4.)



---

# Some additional operations

In [188]:
important = torch.Tensor([[0,0,0],[1,1,1],[0,0,1]])
print (important)

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [0., 0., 1.]])


In [189]:
print (important.reshape(-1))

tensor([0., 0., 0., 1., 1., 1., 0., 0., 1.])


In [190]:
important2 = important.transpose(0,1)
important2

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 1.]])

In [191]:
important2.reshape(-1) #note the difference between the above!!!

tensor([0., 1., 0., 0., 1., 0., 0., 1., 1.])

In [192]:
realisticDimensions = torch.rand(128,20,4096) #for instance transformer encoder input: batchsize, sequence length, embedding size
realisticDimensions.shape

torch.Size([128, 20, 4096])

Due to huge Tensor size, it is impossible to check for individual values. Use shape for sanity checks, but be aware that some bugs might be well hidden and cannot be seen via shape only!!!

In [193]:
realisticDimensions

tensor([[[0.2388, 0.0301, 0.2835,  ..., 0.1729, 0.7503, 0.1506],
         [0.0796, 0.7688, 0.2944,  ..., 0.5532, 0.9049, 0.5915],
         [0.1404, 0.0793, 0.6522,  ..., 0.1327, 0.8668, 0.4910],
         ...,
         [0.8846, 0.5083, 0.8316,  ..., 0.8512, 0.3706, 0.8095],
         [0.2754, 0.5574, 0.8243,  ..., 0.6535, 0.5735, 0.5828],
         [0.5810, 0.6036, 0.7830,  ..., 0.5270, 0.6245, 0.8378]],

        [[0.4599, 0.6467, 0.9132,  ..., 0.1974, 0.0983, 0.4318],
         [0.8395, 0.7466, 0.7304,  ..., 0.3234, 0.9334, 0.6048],
         [0.0910, 0.6753, 0.6564,  ..., 0.7225, 0.4725, 0.6262],
         ...,
         [0.3380, 0.1862, 0.1349,  ..., 0.3745, 0.3579, 0.7520],
         [0.6958, 0.1664, 0.4616,  ..., 0.4674, 0.0107, 0.5615],
         [0.7349, 0.7151, 0.3266,  ..., 0.5317, 0.0643, 0.6551]],

        [[0.7778, 0.1757, 0.4711,  ..., 0.4312, 0.0647, 0.0138],
         [0.0769, 0.6370, 0.4607,  ..., 0.8463, 0.5606, 0.0540],
         [0.8528, 0.7088, 0.6261,  ..., 0.3080, 0.7131, 0.