# **Data Representation - From words to numbers**

**Term Document Matrix:**

Document 1: "The dog is a nice dog"

Document 2: "The ant is no dog"


Algorithm:

```
1. Assign each unique word(=type) from the corpus an index:
      the -> 0
      dog -> 1
      is -> 2
      a -> 3
      nice -> 4
      ant -> 5
      no -> 6

The set of unique words is referred to as the Vocabulary
```



```
2. Create a matrix filled with zeros with the following dimensions:
      rows = number of documents
      columns = size of the vocabulary

Matrix:
            the [0]  dog [1]  is [2]  a [3]  nice [4]  ant [5]  no [6]
Doc 1  [0]       0        0       0      0         0        0        0
Doc 2  [1]       0        0       0      0         0        0        0
```

```
3. Iterate over the words in the documents and increment the values
in the matrix at position (docIndex, wordindex) by one:
"the dog is a nice dog"
=>

            the [0]  dog [1]  is [2]  a [3]  nice [4]  ant [5]  no [6]
Doc 1  [0]       1        2       1      1         1        0        0
Doc 2  [1]       0        0       0      0         0        0        0


"the ant is no dog"
=>

            the [0]  dog [1]  is [2]  a [3]  nice [4]  ant [5]  no [6]
Doc 1  [0]       1        2       1      1         1        0        0
Doc 2  [1]       1        1       1      0         0        1        1
```

The resulting matrix is a so-called "term-document" matrix, where one row represents a document.



In [17]:
import torch
def getDocMatrix():
    ###the documents are represented as a nested list (steps like tokenization etc. are omitted for simplicity)

    documents = [["the","dog","is","a","nice","dog"],["the","ant","is","no","dog"]]

    #determine the amount of documents in documents
    nrDocuments = len(documents)

    #vocabulary = set(sum(documents,[])) #simple, but implicit
    ###explicity determining the vocabulary:

    #init empty vocab
    vocabulary = []

    #iterate over documents
    for document in documents:
      #iterate over words in document
      for token in document:
        #check if a token is in vocabulary - if not, add to vocab
        if not token in vocabulary:
          vocabulary.append(token)
    #print the vocabulary as list
    print (vocabulary)

    #determine the size of the vocabulary
    vocSize = len(vocabulary)
    print (vocSize)

    #create a range of indices needed (i.e. the numbers 0-6)
    indices = range(len(vocabulary))
    print (indices)

    #create a dictionary out of the vocabulary and the range of indices
    vocabularyIndex = dict(zip(vocabulary, indices))
    print (vocabularyIndex)

    #initialize the term document matrix with zeros
    docMatrix = torch.zeros((nrDocuments,vocSize))

    for i, document in enumerate(documents):
        #replace the words in the current document by their respective indices and transform the list to a tensor
        tmp = torch.tensor(list(map(lambda x: vocabularyIndex[x], document)))
        print (f"\nDocument {i} as type indices:")
        print (tmp) #document with words replaced by indices
        oneHot = torch.zeros((tmp.shape[0],len(vocabulary))) #intermediate matrix where each row represents one token
        rows = torch.arange(tmp.shape[0])
        print (f"\nDocument {i} row indices (tokens):")
        print (rows)
        oneHot[rows,tmp] = 1 #
        print (f"\nDocument {i} as one-hot encoded word vectors:")
        print (oneHot)
        docVector = torch.sum(oneHot,0) #document representation as sum of the one-hot encoded token representations
        docMatrix[i] = docVector
    print ("\nThis is the term-document matrix:")
    return (docMatrix)
docMatrix = getDocMatrix()
print (docMatrix)

['the', 'dog', 'is', 'a', 'nice', 'ant', 'no']
7
range(0, 7)
{'the': 0, 'dog': 1, 'is': 2, 'a': 3, 'nice': 4, 'ant': 5, 'no': 6}

Document 0 as type indices:
tensor([0, 1, 2, 3, 4, 1])

Document 0 row indices (tokens):
tensor([0, 1, 2, 3, 4, 5])

Document 0 as one-hot encoded word vectors:
tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.]])

Document 1 as type indices:
tensor([0, 5, 2, 6, 1])

Document 1 row indices (tokens):
tensor([0, 1, 2, 3, 4])

Document 1 as one-hot encoded word vectors:
tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0.]])

This is the term-document matrix:
tensor([[1., 2., 1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0., 1., 1.]])


TF-IDF: Taking into account rare words and text length

Side effect: Normalization and "better" value range

In [27]:
print ("Term-Document Matrix")
print (docMatrix)
#Word frequency for whole corpus:
wf = torch.sum(docMatrix,0)
#Nr. of words per document
wc = torch.sum(docMatrix,1)
print ("\nHow often does a token occur in the corpus:")
print (wf)
print ("\nHow many words are in the respective documents:")
print (wc)
#term frequency
tf = torch.div(docMatrix.transpose(0,1),wc)
tf = tf.transpose(0,1)
print ("\nNormalise token frequency by document length:")
print (tf)

#document frequency
df = torch.count_nonzero(docMatrix,0)
print ("\nIn how many documents of the corpus does a token occur:")
print (df)

#inverse document frequency
idf = docMatrix.shape[0]/df+1 #+1 to avoid division by zero errors
print ("\nInverse of the document frequency:")
print (idf)
#log idf
logIdf = torch.log(idf) #taking the logarithm
print ("\nLog inverse document frequency: (specificity of a term)")
print (logIdf)

#tf-idf
tfidf = tf*logIdf
print ("\nTF-IDF - Term Frequency * Term Specificity")
print (tfidf)

Term-Document Matrix
tensor([[1., 2., 1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0., 1., 1.]])

How often does a token occur in the corpus:
tensor([2., 3., 2., 1., 1., 1., 1.])

How many words are in the respective documents:
tensor([6., 5.])

Normalise token frequency by document length:
tensor([[0.1667, 0.3333, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.2000, 0.2000]])

In how many documents of the corpus does a token occur:
tensor([2, 2, 2, 1, 1, 1, 1])

Inverse of the document frequency:
tensor([2., 2., 2., 3., 3., 3., 3.])

Log inverse document frequency: (specificity of a term)
tensor([0.6931, 0.6931, 0.6931, 1.0986, 1.0986, 1.0986, 1.0986])

TF-IDF - Term Frequency * Term Specificity
tensor([[0.1155, 0.2310, 0.1155, 0.1831, 0.1831, 0.0000, 0.0000],
        [0.1386, 0.1386, 0.1386, 0.0000, 0.0000, 0.2197, 0.2197]])
