In [ ]:
import numpy as np
"""
Demonstrates iterating over a sliced NumPy array using np.nditer.
np.nditer does not return sliced views, but iterates over the elements of the sliced array.
"""
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

# sliced array with step size 2 in second dimension
sub = arr[:, ::2]
print("Sliced array with step size 2 in second dimension:")
print(sub)  

In [ ]:
"""Demonstrate basic enumeration in python."""
for index, value in enumerate(['a', 'b', 'c']):
    print(index, value)

In [ ]:
"""And lets enumerate with numpy array."""
arr = np.array([10, 20, 30])
for index, value in np.ndenumerate(arr):
    print(index, value)

# 2D array enumeration
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

In [ ]:
"""Demonstrate concatenation of two numpy arrays along a specified axis.
what is axis?
Axis 0 is the first dimension (rows), axis 1 is the second dimension (columns).
"""
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr_concat_axis_1 = np.concatenate((arr1, arr2), axis=1) # concatenate along columns
arr_concat_axis_0 = np.concatenate((arr1, arr2), axis=0) # concatenate along rows

print(arr_concat_axis_1)
print(arr_concat_axis_0)

In [ ]:
"""Demo of array splitting using numpy"""
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
# Split the array into 2 sub-arrays along axis 0 (rows)
sub_arrays = np.array_split(arr, 2, axis=0)
print("Splitting along axis 0:")
for sub in sub_arrays:
    print(sub)

# Split the array into 2 sub-arrays along axis 1 (columns)
sub_arrays = np.array_split(arr, 2, axis=1)
print("Splitting along axis 1:")
for sub in sub_arrays:
    print(sub)

In [ ]:
"""Demo array searching using numpy """
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 3, 2, 1])
# Find indices where the value is 3
indices = np.where(arr == 3)
print("Indices of elements equal to 3:", indices[0])

In [7]:
import numpy as np
a = np.array([1, 2, 3])
print(f"a: {a}, type: {type(a)}")
print(f"a.shape: {a.shape}")
print(f"a.ndim: {a.ndim}")

b = a[:, np.newaxis]
print(f"b: {b}, type: {type(b)}")
print(f"b.shape: {b.shape}")
print(f"b.ndim: {b.ndim}")


c = a[np.newaxis, :]
print(f"c: {c}, type: {type(c)}")
print(f"c.shape: {c.shape}")
print(f"c.ndim: {c.ndim}")

mesh_a, mesh_b = np.meshgrid(a, b)
print(f"mesh_a: {mesh_a}, type: {type(mesh_a)}")
print(f"mesh_a.shape: {mesh_a.shape}")
print(f"mesh_a.ndim: {mesh_a.ndim}")

print(f"mesh_b: {mesh_b}, type: {type(mesh_b)}")
print(f"mesh_b.shape: {mesh_b.shape}")
print(f"mesh_b.ndim: {mesh_b.ndim}")

a: [1 2 3], type: <class 'numpy.ndarray'>
a.shape: (3,)
a.ndim: 1
b: [[1]
 [2]
 [3]], type: <class 'numpy.ndarray'>
b.shape: (3, 1)
b.ndim: 2
c: [[1 2 3]], type: <class 'numpy.ndarray'>
c.shape: (1, 3)
c.ndim: 2
mesh_a: [[1 2 3]
 [1 2 3]
 [1 2 3]], type: <class 'numpy.ndarray'>
mesh_a.shape: (3, 3)
mesh_a.ndim: 2
mesh_b: [[1 1 1]
 [2 2 2]
 [3 3 3]], type: <class 'numpy.ndarray'>
mesh_b.shape: (3, 3)
mesh_b.ndim: 2
